export const TanStackQueryKey = {
  auth: 'auth',
  logout: 'logout',
  profile: 'profile',
  getUser: 'getUser',
  getUsers: 'getUsers',
  createUser: 'createUser',
  updateUser: 'updateUser',
  deleteUser: 'deleteUser',
  getApplications: 'getApplications',
  createApplication: 'createApplication',
  sendStatus: 'sendStatus',
  getEventById: 'getEventById',
  getEvents: 'getEvents',
  createEvent: 'createEvent',
  updateEvent: 'updateEvent',
  getReservationByUserId: 'getReservationByUserId',
  deleteEvent: 'deleteEvent',
  getReservations: 'getReservations',
  getCategories: 'getCategories',
  createCategory: 'createCategory',
  updateCategory: 'updateCategory',
  deleteCategory: 'deleteCategory'
}
